const STRUCTURE_TIMEFRAMES = Object.freeze([
  { label: '4H', interval: '240', minutes: 240 },
  { label: '1H', interval: '60', minutes: 60 },
  { label: '15m', interval: '15', minutes: 15 },
]);

module.exports = {
  STRUCTURE_PROJECT: 'STRUCTURE',
  STRUCTURE_EXPERIMENT_ID: 'STRUCTURE_V1_DATA_AUDIT_20260731',
  STRUCTURE_LEVEL_EXPERIMENT_ID: 'STRUCTURE_V1_LEVEL_RESEARCH_20260731',
  STRUCTURE_TIMEFRAMES,
  STRUCTURE_AUDIT_CANDLE_LIMIT: 200,
  STRUCTURE_AUDIT_MIN_CONFIRMED_CANDLES: 180,
  STRUCTURE_LEVEL_ENGINE_ENABLED: true,
  STRUCTURE_WIDE_SCAN_ENABLED: false,
  STRUCTURE_EVENT_TRACKING_ENABLED: false,
  STRUCTURE_PAPER_SIGNALS_ENABLED: false,
  STRUCTURE_ALERTS_ENABLED: false,
};
